[package]
name = "sangnak"
version = "0.1.0"
authors = ["Piyush Mishra <piyush.raj.kit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "8.2.0"
clap = "2.33.3"